name: Deploy Staging on Webserver via SFTP
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "build/**/*"
          target: ${{ secrets.REMOTE_TARGET }}
